version: '3.9'
services:
  db:
    image: postgres:17
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Sumedha1234
      POSTGRES_DB: mydb
    
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: url-shortner
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: Sumedha1234
      DB_NAME: mydb
volumes:
  pgdata:



