apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: db-externalsecret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: kv/url-shortner/creds
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef: 
        key: kv/url-shortner/creds
        property: DB_PASSWORD
