apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault: 
      server: "http://host.docker.internal:8200"

      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token

---

apiVersion: v1
kind: Secret
metadata:
  name: vault-token
type: Opaque
stringData:
  token: root 

